name: Generate MP3 Visualizer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ffmpeg
          pip install -r requirements.txt

      - name: Setup Google Drive API
        run: |
          cat <<EOF > credentials.json
${{ secrets.DRIVE_API_JSON }}
EOF

      - name: Run Visualizer Script
        run: |
          python visualizer.py
